# Generated by Django 3.2.4 on 2021-06-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dolgozo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torzsszam', models.CharField(max_length=6)),
                ('vnev', models.CharField(max_length=50)),
                ('knev', models.CharField(max_length=50)),
                ('telefonszam', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
                ('jogosultsag', models.CharField(choices=[('A', 'Adminisztrátori'), ('F', 'Felügyeleti'), ('O', 'Olvasási')], max_length=1)),
            ],
        ),
    ]
