# Generated by Django 2.2.12 on 2021-06-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tervtarapp', '0002_auto_20210622_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Felhasznalo',
            fields=[
                ('felhnev', models.CharField(default='Default', max_length=25, primary_key='True', serialize=False)),
                ('jelszo', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Dolgozo',
        ),
    ]
