# Generated by Django 3.2.4 on 2021-06-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tervtarapp', '0003_auto_20210622_1015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Felhasznalo',
        ),
    ]
