# Generated by Django 3.2.4 on 2021-06-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tervtarapp', '0004_delete_felhasznalo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Felhasznalo',
            fields=[
                ('Felhasználónév', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Jelszó', models.CharField(max_length=25)),
                ('Jogosultság', models.CharField(choices=[('A', 'Adminisztrátori'), ('M', 'Módosítási és olvasási'), ('O', 'Olvasási')], max_length=1)),
            ],
        ),
    ]
