# Generated by Django 3.2.4 on 2021-06-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tervtarapp', '0005_felhasznalo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Felhasznalo',
        ),
    ]
