# Generated by Django 3.2.4 on 2021-06-28 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tervtarapp', '0006_delete_felhasznalo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egyseg',
            fields=[
                ('megnevezes', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vonal',
            fields=[
                ('vonalszam', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('kezdo_allomas', models.CharField(max_length=50)),
                ('vegallomas', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dokumentumtipus',
            fields=[
                ('megnevezes', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('egyseg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tervtarapp.egyseg')),
            ],
        ),
        migrations.CreateModel(
            name='Allomas',
            fields=[
                ('allomasnev', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('vonalszam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tervtarapp.vonal')),
            ],
        ),
    ]
