# Generated by Django 3.2.4 on 2021-06-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tervtarapp', '0007_allomas_dokumentumtipus_egyseg_vonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vonal',
            name='vonalszam',
            field=models.IntegerField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
