# Generated by Django 3.2.4 on 2021-06-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tervtarapp', '0008_alter_vonal_vonalszam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vonal',
            options={'ordering': ['vonalszam']},
        ),
        migrations.AlterField(
            model_name='vonal',
            name='vonalszam',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
