# Generated by Django 3.2.4 on 2021-06-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tervtarapp', '0009_auto_20210628_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vonal',
            options={},
        ),
    ]
