# Generated by Django 3.2.4 on 2021-06-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tervtarapp', '0010_alter_vonal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vonal',
            name='vonalszam',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
